version: '3'
services:
 backend:
  build:
    context: .
    dockerfile: packages/backend/Dockerfile
  ports:
    - "3567:3567"
 frontend:
  build:
    context: .
    dockerfile: packages/frontend/Dockerfile
  ports:
     - "8844:80"